import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ASSETS_DIR = os.path.join(BASE_DIR, "assets")
SAVES_DIR = os.path.join(BASE_DIR, "saves")
FONT_PATH = os.path.join(ASSETS_DIR, "font", "MPLUS1p-Regular.ttf")

ICON_PATH = os.path.join(ASSETS_DIR, "icon.ico")
WALLPAPER_PATH = os.path.join(ASSETS_DIR, "wallpaper.png")
BACKGROUND_PATH = os.path.join(ASSETS_DIR, "Background.png")

GENEROS = [
    "RPG",
    "Action RPG",
    "RPG de Turno",
    "RPG Tático",
    "JRPG",
    "Action JRPG",
    "JRPG de Turno",
    "JRPG Tático",
    "Dungeon Crawler",
    "MMORPG",
    "True RPG",
    "Aventura",
    "Aventura Gráfica",
    "Point and Click",
    "Metroidvania",
    "Survival Horror",
    "Ação",
    "Hack and Slash",
    "Beat 'em Up",
    "Stealth",
    "Action-Adventure",
    "Estratégia",
    "RTS (Real-Time Strategy)",
    "TBS (Turn-Based Strategy)",
    "Tower Defense",
    "4X",
    "Simulação",
    "Simulação de Vida",
    "Simulação de Construção",
    "Simulação de Negócios",
    "Simulação de Voo",
    "Simulação de Veículos",
    "Simulação Social",
    "Esportes",
    "Futebol",
    "Basquete",
    "Corrida",
    "Golfe",
    "Tênis",
    "Esportes Radicais",
    "Automobilismo",
    "Futebol Americano",
    "Puzzle",
    "Quebra-Cabeças Lógicos",
    "Match-3",
    "Jogos de Palavras",
    "Sokoban",
    "Escape Room",
    "Luta",
    "2D Fighting",
    "3D Fighting",
    "Arena Fighting",
    "Party Fighting",
    "Tiro",
    "FPS (First-Person Shooter)",
    "TPS (Third-Person Shooter)",
    "Shoot 'em Up",
    "Boomer Shooter",
    "Bullet Hell",
    "Horror",
    "Psychological Horror",
    "Action Horror",
    "VR Horror",
    "Sandbox",
    "World Builder",
    "Exploration",
    "Open World",
    "Criativo",
    "Jogos de Festa",
    "Minigames",
    "Quiz",
    "Jogos de Tabuleiro Adaptados",
    "Educação",
    "Treinamento",
    "Documentário",
    "Outro",
]

PLATAFORMAS = [
    "Atari 2600",
    "Atari 5200",
    "Atari 7800",
    "NES (Nintendo Entertainment System)",
    "SNES (Super Nintendo Entertainment System)",
    "Virtual Boy",
    "Nintendo 64",
    "GameCube",
    "Nintendo Wii",
    "Nintendo WiiU",
    "Game Boy",
    "Game Boy Color",
    "Game Boy Advance",
    "Nintendo DS",
    "Nintendo 3DS/2DS",
    "Nintendo Switch",
    "Sega Master System",
    "Sega Genesis (Mega Drive)",
    "Game Gear",
    "Sega Nomad",
    "Sega Saturn",
    "Sega Dreamcast",
    "PlayStation 1",
    "PlayStation 2",
    "PlayStation Portable",
    "PlayStation 3",
    "PlayStation Vita",
    "PlayStation 4",
    "PlayStation 5",
    "Xbox Clássico",
    "Xbox 360",
    "Xbox One",
    "Xbox Series X|S",
    "Neo Geo",
    "Neo Geo Pocket",
    "Neo Geo Pocket Color",
    "Neo Geo X",
    "TurboGrafx-16 (PC Engine)",
    "TurboGrafx-CD",
    "Intellivision",
    "ColecoVision",
    "Commodore 64",
    "Amiga",
    "ZX Spectrum",
    "3DO",
    "WonderSwan",
    "WonderSwan Color",
    "PC",
    "Mobile",
    "Outro",
]
